### ISSUE TITLE
answers are not processed if they use template

### ISSUE THREAD

**Issue by 12rambau** [12rambau/pytest-copie#38]
using the following default copier.yml: 

```yaml
# questions
project_name:
  typr: str
  default: "Package skeleton"
  help: "The name of the project"

github_repo_name:
  type: str
  default: "{{ project_name.lower().replace(' ', '-') }}"
  help: "The name of the GitHub repository"

project_slug:
  type: str
  default: "{{ github_repo_name.lower().replace('-', '_') }}"
  help: "The slug that will be used to name the lib package"
```

will not replace the values in the default. making them impossible to use.
